#!/bin/bash

: ${RUBY_VERSION:="3.2"}
docker build -t github-pages-health-check --build-arg RUBY_VERSION=$RUBY_VERSION .
if [ -n "$DEBUG" ]; then
  # Run a shell.
  docker run -e RUBY_VERSION -it --rm -v $(pwd):/app/github-pages-health-check github-pages-health-check
else
  # Run CI
  docker run -e RUBY_VERSION --rm github-pages-health-check script/cibuild --profile --fail-fast
fi
