#!/bin/sh

set -ex

script/bootstrap

echo "Using RUBY_VERSION=$RUBY_VERSION"

script/test-redirections &
script/test $@
script/check-cdn-ips
bundle exec script/check www.parkermoore.de | grep 'valid?: true'
bundle exec script/check ben.balter.com | grep 'valid?: true'
bundle exec gem build github-pages-health-check.gemspec
