name: Publish Gem

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Ruby
        uses: ruby/setup-ruby@bec3f19a76460dbe12f60def7d1a77585f07516c # v1.322.0
        with:
          ruby-version: '3.3'
      - name: Build gem
        run: |
          gem build github-pages-health-check.gemspec
      - name: Publish gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.PAGES_GEM_PUBLISHING }}
        run: |
          gem push github-pages-health-check-*.gem
