on: push
name: "GitHub Pages Health Check Tests"
permissions:
  contents: read
jobs:
  build:
    name: "GitHub Pages Health Check Tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
    steps:
    - uses: actions/checkout@master
    - name: script/cibuild-docker
      run: script/cibuild-docker
      env:
        RUBY_VERSION: ${{ matrix.ruby }}
